Add SAML auth configuration
concourse/concourse-chart pull request #143
Opened 2020-09-01 16:14 UTC by aoldershaw

# Why do we need this PR?

Needed after concourse/concourse#5998 was merged

# Changes proposed in this pull request

* Add the flags required for SAML auth

# Contributor Checklist

- [x] Variables are documented in the `README.md` (seems like pretty much only secrets are documented?)
- [x] Which branch are you merging into?
    - `master` is for changes related to the current release of the `concourse/concourse:latest` image and should be good to publish immediately
    - `dev` is for changes related to the next release of Concourse (aka unpublished code on `master` in [concourse/concourse](https://github.com/concourse/concourse))

# Reviewer Checklist
> This section is intended for the core maintainers only, to track review progress. Please do not
> fill out this section.
- [ ] Code reviewed
- [ ] Topgun tests run
- [ ] Back-port if needed
- [ ] Is the correct branch targeted? (`master` or `dev`)

2020-09-02 21:28 UTC, jamieklassen requested changes
Maybe just change a comment?

2020-09-02 21:28 UTC, jamieklassen commented on values.yaml
> +          user:
is it worth mentioning that this should be a string which contains a comma-separated list of... _allow_ listed SAML users? I've seen users get confused since "List" tends to intuitively translate to "YAML array".

2020-09-08 01:48 UTC, aoldershaw commented on values.yaml
> +          user:
Updated to `Comma-separated allow list of ... users` - hoping that's clear enough to use a string. If not, let me know, and we can rethink the wording

2020-09-08 12:45 UTC, jamieklassen approved these changes

2020-09-08 12:46 UTC, merged