Add ability to define annotations for web/worker Service accounts
concourse/concourse-chart pull request #171
Opened 2020-10-28 20:18 UTC by Caprowni

# Why do we need this PR?

Currently there is no way to add any annotations to service accounts for either the web or the worker, I have a use case whereby I need to add some annotations(specifically for EKS IAM Roles) and as a workaround had to create my own service accounts and change the default ones Concourse uses.  Therefore this updates the chart to natively support this feature by definition annotations inside `helpers.tpl` and they will be rendered into the chart at installation time.

# Changes proposed in this pull request

* Adds an annotations variable definition inside `_helpers.tpl` for the web & worker service accounts, they are separate as there may not be a need to include the same annotations on both service accounts etc.
* Adds the annotation include statements into the web and worker service account template files. 

# Contributor Checklist
<!--
Are the following items included as part of this PR? Please delete checkbox items that don't apply.
--
- [master] Which branch are you merging into?
    - `master` is for changes related to the current release of the `concourse/concourse:latest` image and should be good to publish immediately

Merging to master should be okay (?) happy to move to dev if need be, as I mentioned i've already worked around this by creating my own service accounts but would be nice to have this natively supported.

# Reviewer Checklist
> This section is intended for the core maintainers only, to track review progress. Please do not
> fill out this section.
- [ ] Code reviewed
- [ ] Topgun tests run
- [ ] Back-port if needed
- [ ] Is the correct branch targeted? (`master` or `dev`)

2020-11-04 17:46 UTC, YoussB requested changes
Thanks @Caprowni.
The PR looks good to me, I added a couple of small indentation suggestions.
Also, can you add the new parameter to `values.yml`

2020-11-04 17:46 UTC, YoussB commented on templates/web-serviceaccount.yaml
> +  {{- end -}}
```suggestion
    {{- end -}}
```
just a minor indentation

2020-11-04 17:46 UTC, YoussB commented on templates/worker-serviceaccount.yaml
> +{{- if .Values.rbac.workerServiceAccountAnnotations }}
```suggestion
    {{- if .Values.rbac.workerServiceAccountAnnotations }}
```

2020-11-04 21:26 UTC, Caprowni commented
@YoussB Hey! Thanks for reviewing my PR, I fixed the indentation you mentioned, i'm not sure about the values.yaml comment though as i've already added the definitions into the values.yaml at the root of the repo.

Is there something i've missed?

2020-11-06 18:32 UTC, YoussB approved these changes
@Caprowni, sorry I probably missed that. I think this is good to go.

2020-11-06 18:33 UTC, merged