Remove duplicate key in values.yml
concourse/concourse-chart pull request #218
Opened 2021-03-14 15:36 UTC by ionphractal

# Existing Issue
no

# Why do we need this PR?
The values.yml contains a duplicate key which can irritate parsers as well as human readers.

# Changes proposed in this pull request
Remove the duplicate key in values.yml

# Contributor Checklist

- [x] Variables are documented in the `README.md`
    - unchanged: no additional variable, none removed
- [x] Which branch are you merging into?
    - `master`

# Reviewer Checklist
> This section is intended for the core maintainers only, to track review progress. Please do not
> fill out this section.
- [ ] Code reviewed
- [ ] Topgun tests run
- [ ] Back-port if needed
- [ ] Is the correct branch targeted? (`master` or `dev`)

2021-03-15 17:58 UTC, taylorsilva requested changes
yup, human error, we totally added this flag twice. It's also duplicated in the `template/web-deployment.yaml` on lines 1258-1261. Could you remove those too?

What parser did you use to find this?

First commit: https://github.com/concourse/concourse-chart/commit/9141dcd0544238d337030061821a79aa72acca93
Second commit: https://github.com/concourse/concourse-chart/commit/d2560637e5acfa109dd52fe415c4dddfd173eefe

2021-03-18 10:28 UTC, ionphractal commented
> yup, human error, we totally added this flag twice. It's also duplicated in the `template/web-deployment.yaml` on lines 1258-1261. Could you remove those too?
> 
> What parser did you use to find this?
> 
> First commit: [9141dcd](https://github.com/concourse/concourse-chart/commit/9141dcd0544238d337030061821a79aa72acca93)
> Second commit: [d256063](https://github.com/concourse/concourse-chart/commit/d2560637e5acfa109dd52fe415c4dddfd173eefe)

Also removed the lines in web-deployment.yml.
My actual issue was having concourse manually deployed with a custom values.yml through helm and then trying to manage it with kubeapps threw an error in kubeapps about the duplicate key when trying to upgrade the deployment.
Another error came up when I tried to compare different versions. For that I wanted to sort the yaml file. It worked with "bosh int" but it threw an error on vscode [YAML Sort](https://marketplace.visualstudio.com/items?itemName=PascalReitermann93.vscode-yaml-sort) plugin.

2021-03-19 13:57 UTC, clarafu approved these changes
Looks great, thanks for catching this!

2021-03-19 14:59 UTC, taylorsilva approved these changes

2021-03-19 14:59 UTC, merged