Allow adding custom worker certs that all container can inherit
concourse/concourse-chart pull request #244
Opened 2021-04-19 04:44 UTC by xtremerui

# Existing Issue
Fixes #https://github.com/concourse/concourse-chart/issues/211.

# Changes proposed in this pull request
User will be able to config a .pem file that contains additional certs that could be added to worker certs pool by specifying a path (default to /etc/ssl/certs/worker-certs.pem). Notice the path has to be a file so it could be additional other than replacing entire /etc/ssl/certs directory.

# Contributor Checklist
- [ ] Variables are documented in the `README.md`
- [ ] Which branch are you merging into?
    - `master` is for changes related to the current release of the `concourse/concourse:latest` image and should be good to publish immediately

# Reviewer Checklist
- [ ] Code reviewed
- [ ] Topgun tests run
- [ ] Back-port if needed
- [ ] Is the correct branch targeted? (`master` or `dev`)

2021-04-19 16:15 UTC, EstebanFS requested changes

2021-04-19 16:15 UTC, EstebanFS commented on README.md
> +| `worker.additionalCertificates` | Enable adding additional certificates to worker certs pool | `false` |
Could you add `worker.workerAdditionalCerts` to the README as well?

2021-04-19 16:15 UTC, EstebanFS commented on templates/web-secrets.yaml
> +  {{- end }}
Why was this added to the web's secrets?

2021-04-20 01:19 UTC, xtremerui commented on README.md
> +| `worker.additionalCertificates` | Enable adding additional certificates to worker certs pool | `false` |
Guess you mean that new secret. I added it above.

2021-04-20 01:20 UTC, xtremerui commented on templates/web-secrets.yaml
> +  {{- end }}
that was dev code that committed accidentally. Thx for catching it.

2021-04-26 16:04 UTC, taylorsilva submitted a review, later dismissed

2021-04-26 16:06 UTC, taylorsilva commented
I'm taking over this PR since Rui is on leave.

2021-04-26 16:14 UTC, EstebanFS approved these changes
LGTM!

2021-04-26 16:14 UTC, EstebanFS commented on README.md
> +| `worker.CertsPath` | Specify the path for additional worker certificates | `/etc/ssl/certs` |
Just a small typo here, should be lower case

2021-04-26 16:21 UTC, merged