Add HPA autoscaling behavior field
concourse/concourse-chart pull request #282
Opened 2021-11-22 21:27 UTC by taylorshaulis

# Why do we need this PR?
This PR adds the behavior field to the worker HPA template.  Once added the behavior field will allow users to adjust scale down and scale up windows beyond the default kubernetes settings.

https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#default-behavior

# Changes proposed in this pull request

* Add spec.behavior field to worker HPA to allow for custom scale behavior

# Contributor Checklist

- [ ] Variables are documented in the `README.md`
- [ ] Which branch are you merging into?
    - `master` is for changes related to the current release of the `concourse/concourse:latest` image and should be good to publish immediately
    - `dev` is for changes related to the next release of Concourse (aka unpublished code on `master` in [concourse/concourse](https://github.com/concourse/concourse))

# Reviewer Checklist
> This section is intended for the core maintainers only, to track review progress. Please do not
> fill out this section.
- [ ] Code reviewed
- [ ] Topgun tests run
- [ ] Back-port if needed
- [ ] Is the correct branch targeted? (`master` or `dev`)

2021-11-22 21:29 UTC, taylorshaulis commented
The sub settings for worker.autoscaling are not documented in the README.md.  If that is necessary I can add documentation for the behavior field.

This is something new so hopefully we can just merge into the master branch without needing to back-port or wait for the next concourse release.

2021-11-25 15:29 UTC, xtremerui commented on values.yaml
> +#        scaleDown:
could you please fix the indent here?

2021-11-25 15:41 UTC, xtremerui requested changes
Thx for the PR. Just small fix then its good.

2021-11-26 21:34 UTC, taylorshaulis commented on values.yaml
> +#        scaleDown:
Nice catch :)

How does it look now?

2021-11-26 22:44 UTC, xtremerui approved these changes

2021-11-26 22:44 UTC, merged