Replace deprecated `.Capabilities.KubeVersion.GitVersion` references
concourse/concourse-chart pull request #353
Opened 2023-11-13 11:40 UTC by silvestre

> Deprecated: use KubeVersion.Version
https://github.com/helm/helm/blob/82195652495d757d87c1a01f640973f20ca141b0/pkg/chartutil/capabilities.go#L82-L83

# Existing Issue

No, I was just confused by the deprecated references while reading the chart

# Why do we need this PR?

Just to remove a use of deprecated helm-builtin

# Changes proposed in this pull request

* `s/.Capabilities.KubeVersion.GitVersion/.Capabilities.KubeVersion.Version/`

# Contributor Checklist

- [ ] Variables are documented in the `README.md`
- [x] Which branch are you merging into?
    - `master` is for changes related to the current release of the `concourse/concourse:latest` image and should be good to publish immediately
    - `dev` is for changes related to the next release of Concourse (aka unpublished code on `master` in [concourse/concourse](https://github.com/concourse/concourse))

# Reviewer Checklist
> This section is intended for the core maintainers only, to track review progress. Please do not
> fill out this section.
- [ ] Code reviewed
- [ ] Topgun tests run
- [ ] Back-port if needed
- [ ] Is the correct branch targeted? (`master` or `dev`)

2024-01-18 22:03 UTC, ns0092 commented
@silvestre 
I see reference of `.Capabilities.KubeVersion.GitVersion` in a few other places too. Like worker-policy.yaml here: https://github.com/concourse/concourse-chart/blob/2e71523057688a6f5396b6403d5f9a0e958c2a86/templates/worker-policy.yaml#L2

2025-02-04 19:11 UTC, taylorsilva requested changes
@silvestre Thanks for the PR! As the other person noted, you missed one spot in `worker-policy.yaml`. If you update that too then I'll merge this.

2025-02-06 16:38 UTC, silvestre commented
@taylorsilva : I've updated the missing file as well. Thanks!

2025-02-12 21:33 UTC, taylorsilva approved these changes

2025-02-12 21:33 UTC, merged